# -*- coding: utf-8 -*-
"""demsionalidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXOumAd_a9BJV7I0WDXHehQtEfPfAVEd
"""

from google.colab import files

# --- Paso 1: Subir imagen BMP ---
uploaded = files.upload()  # selecciona tu archivo BMP desde tu PC
entrada = list(uploaded.keys())[0]  # nombre del archivo subido
print(f"Imagen cargada: {entrada}")

# --- Funciones de conversión ---
def to_grayscale_value(r, g, b):
    return int(round(0.299*r + 0.587*g + 0.114*b))

def to_black_and_white(val, threshold=128):
    return 255 if val > threshold else 0

def convert_bmp(in_path, out_gray, out_bw, threshold=128):
    with open(in_path, 'rb') as f:
        header = f.read(14)
        dib_header = f.read(40)

        pixel_offset = int.from_bytes(header[10:14], 'little')
        width = int.from_bytes(dib_header[4:8], 'little', signed=True)
        height = int.from_bytes(dib_header[8:12], 'little', signed=True)
        bpp = int.from_bytes(dib_header[14:16], 'little')
        compression = int.from_bytes(dib_header[16:20], 'little')

        if compression != 0 or bpp != 24:
            raise ValueError("Solo BMP 24 bits sin compresión.")

        row_bytes = width * 3
        padding = (4 - (row_bytes % 4)) % 4
        bottom_up = height > 0
        height = abs(height)

        f.seek(pixel_offset)
        pixel_data = []
        for _ in range(height):
            row = bytearray(f.read(row_bytes))
            pad = f.read(padding)
            pixel_data.append((row, pad))

    # --- generar grises y blanco/negro ---
    gray_data, bw_data = [], []
    for row, pad in pixel_data:
        row_gray = bytearray(row)  # copia
        row_bw = bytearray(row)    # copia
        for i in range(0, len(row), 3):
            b, g, r = row[i], row[i+1], row[i+2]
            gray = to_grayscale_value(r, g, b)
            bw = to_black_and_white(gray, threshold)

            # escala de grises
            row_gray[i:i+3] = bytes((gray, gray, gray))
            # blanco y negro
            row_bw[i:i+3] = bytes((bw, bw, bw))
        gray_data.append((row_gray, pad))
        bw_data.append((row_bw, pad))

    # --- guardar gris ---
    with open(out_gray, 'wb') as out:
        with open(in_path, 'rb') as f:
            headers = f.read(pixel_offset)
        out.write(headers)
        rows = gray_data if bottom_up else reversed(gray_data)
        for row, pad in rows:
            out.write(row)
            out.write(pad)

    # --- guardar blanco/negro ---
    with open(out_bw, 'wb') as out:
        with open(in_path, 'rb') as f:
            headers = f.read(pixel_offset)
        out.write(headers)
        rows = bw_data if bottom_up else reversed(bw_data)
        for row, pad in rows:
            out.write(row)
            out.write(pad)

# --- Ejecutar conversión ---
convert_bmp(entrada, "gris.bmp", "blanco_negro.bmp", threshold=128)
print("Conversión completada ✅")

# --- Descargar resultados ---
files.download("gris.bmp")
files.download("blanco_negro.bmp")